insert into sdfull values (1,1986,"R5A",1,"BRAUNSTEINER","GEROLD","","x",2011,"Selbständig und angestellt","","Software (= psychotherapie & Seelsorge)","","2000","Stockerau","Schiesstaltgasse 10 & Kirchenplatz 3","N","N","N","","gernold.braunsteiner@ptz.at","","");
insert into sdfull values (2,1986,"R5A",2,"BUEGER","JOSEF","","",2011,"Kapsch Traffic AG","","Entwicklung emmbedded Systems","","1121","Wien","AmEuroplatz 2","J","N","N","","josef.buerger@speed.at","","");
insert into sdfull values (3,1986,"R5A",3,"DREISZKER","DIETER","","x",2011,"PKE  Electronics AG","","Assistent der Geschäftsleitung","","","","Computerstraße 6","N","N","N","","D.Dreiszker@pke.at","","");
insert into sdfull values (4,1986,"R5A",4,"GEISCHLAEGER","FRANZ","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (5,1986,"R5A",5,"Grimus","Martin","","x",2011,"Grimus","grimus@gw-a.at","Management","","1030","Wien","Inanbenstraße 1/10","N","N","N","","grimus@gw-a.at","","");
insert into sdfull values (6,1986,"R5A",6,"HOCHSCHOPF","NORBERT","","",2011,"Microsoft","","Verkauf","","","Wien","","N","N","N","","norbert.Hochschopf@gmx.at","","");
insert into sdfull values (7,1986,"R5A",7,"KERSCHBAUM","RUPERT","","x",2011,"Metro Automation","","Verkauf","","1030","Wien","Franzosengraben 12","N","N","N","","rupert.kerschbaum@metso.com","","");
insert into sdfull values (8,1986,"R5A",8,"KIETREIBER","JOSEF","","",2011,"Bundesimmobilienges.","","Management","","","","","","","","","Jkietreiber@gmx.at","","");
insert into sdfull values (9,1986,"R5A",9,"KOPP","GERHARD","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (10,1986,"R5A",10,"LEHRBAUM","MARTIN","","x",2011,"Kapsch ","","Management","","1120","Wien","Am Europlatz 5","J","J","J","","martin.Lehrbaum@kapsch.net","","");
insert into sdfull values (11,1986,"R5A",11,"MARGESIC","THOMAS","","",2011,"STQ Sicherheitstechnik GmbH","","Sicherheitstechnik","","1020","Wien","Hofenedergasse 3","N","N","N","","thomas.magesic@gmx.at","","");
insert into sdfull values (12,1986,"R5A",12,"PAUL","CHRISTIAN","","",2011,"Optiker Lang","","MS 97-2010 Service 2008","","2020","Wien","Spatgassepesse 27","N","N","N","","ingcpaul@at.net","","");
insert into sdfull values (13,1986,"R5A",13,"PRINZ","HELMUT","","x",2011,"Sanoway GmbH","","Verteieh Garten und Landwirtschaftsprodukte","","6850","Dornbirn","Bildgasse 12","N","N","N","","helmut.prinz@direkt.at","","");
insert into sdfull values (14,1986,"R5A",14,"Sadofsky","Alexander","","",2011,"Siemens","","Software/Management","","1210","Wien","Ruthnergasse 3","N","N","N","","alexander@sadofsky.at","","");
insert into sdfull values (15,1986,"R5A",15,"WEISSENBERGER","PETER","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (16,1986,"R5A",16,"Wiesauer","Kurt","","x",2011,"Sitexs-Databusimess IT Solution","","Management/Verrtrieb/Marketing","","1230","Wien","Richard Straußstrasse 43","","N","N","","kurt.wiesauer@gmx.at","","");
insert into sdfull values (17,1986,"R5B",1,"FREUND","JOSEF","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (18,1986,"R5B",2,"HAHN","MANFRED","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (19,1986,"R5B",3,"HOCHSTOEGER","STEFAN","","x",2011,"Kapsch TrafficCom","","Software-Analyse (Design), technische Projektleitung","","1120","Wien","AmEuroplatz 2","N","","J","","Stefan.Hochstoeger@kapsch.net","","");
insert into sdfull values (20,1986,"R5B",4,"HOEGER","FRANZ","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (21,1986,"R5B",5,"HOELZL","PETER","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (22,1986,"R5B",6,"HOERMANN","HUBERT","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (23,1986,"R5B",7,"HOERSCHLAEGER","JOHANNES","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (24,1986,"R5B",8,"HOFER","KLAUS","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (25,1986,"R5B",9,"Hofmann","Philipp","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (26,1986,"R5B",10,"Kneissl","Roland","","x",2011,"gemdatNÖ","","Installation und Betreuung von kleinen Netzwerken, Hard- und Softwareintegration","","2180","Korneuburg","Girakstraße 7","N","N","N","","roland.Kneissl@aon.at","","");
insert into sdfull values (27,1986,"R5B",11,"Köppl","Helfried","","x",2011,"EGSTON","","Projektmanagament","","3730","Eggenburg","Grafenbergerstraße 9","J","J","J","","Helios@europemail.com","","");
insert into sdfull values (28,1986,"R5B",12,"MIKOLASCHEK","GUENTER","","verstorben",0,"","","","","","","","","","","","","","");
insert into sdfull values (29,1986,"R5B",13,"Nikowitsch","Martin","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (30,1986,"R5B",14,"PFEIFFER-VOGL","PETER","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (31,1986,"R5B",15,"REITER","KLAUS","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (32,1986,"R5B",16,"TROLLMANN","WILFRIED","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (33,1986,"R5B",17,"Würrer","Günter","","x",2011,"Siemens","","In Betreibnahme von Maschinen","","","","","J","N","N","","Guenter.Wuerrer@siemens.com","","");
insert into sdfull values (34,1986,"R5B",18,"ZEITLBERGER","LEOPOLD","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (35,1991,"R5A",1,"BOCK","STEFAN","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (36,1991,"R5A",2,"Hewarth","Michael","","x",2011,"Hagenberg Software GmbH","","Software Entwicklung","","","","Softwarepark 35","J","J","N","","michaelhewarth@gmx.at","","");
insert into sdfull values (37,1991,"R5A",3,"HOCHSTÖGER","THOMAS","","",2011,"ABB-Robotertechnik","","","","","Wiener Neudorf","Bnowerboveric 1","J","N","J","","thomas.hochstoeger@ataabb.com","","");
insert into sdfull values (38,1991,"R5A",4,"HUBER","THOMAS","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (39,1991,"R5A",5,"Liemberger","Karl","","x",2011,"3KL EDV Consulting GmbH","","SAP, Projektleitung","","3812","Ellends","Ellends 56","N","J","N","","karl.liemberger@gmx.at","","");
insert into sdfull values (40,1991,"R5A",6,"Meierhofer","Andreas","","",2011,"Test-Fuchs","","Soft- und Hardware","","3812","Groß Sieghants","","J","J","J","","a.meierhofer@gmx.at","","");
insert into sdfull values (41,1991,"R5A",7,"Pinger","Reinhard","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (42,1991,"R5A",8,"PIRINGER","LEOPOLD","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (43,1991,"R5A",9,"REIM","CHRISTIAN","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (44,1991,"R5A",10,"Stampfl","Norbert","","x",2011,"Frequentis","","","","1100","Wien 10","","J","N","J","","norbert.@stampfl@frequentis.com","","");
insert into sdfull values (45,1991,"R5A",11,"TRUMMER","ROBERT","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (46,1991,"R5A",12,"WALZER","RAINER","","x",2011,"Tele 2","","VOIP","","","","","J","N","N","","rainer.walzer@uta.at","","");
insert into sdfull values (47,1991,"R5A",13,"WANZENBÖCK","THOMAS","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (48,1991,"R5A",14,"ZECHMEISTER","ANDREAS","Ing","",2011,"Wiener Urankenanstaunecerbund-IT","","SAP Business Warehouse","","1030","Wien","Viehmarktgasse","","N","N","","andreas.zechmeister@wienkav.at","","");
insert into sdfull values (49,1991,"R5B",1,"BAYER","STEFAN","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (50,1991,"R5B",2,"Becher","Werner","","x",2011,"Adessa Austria gmbH","","Gründer und Eigentühmer meherer Unternehmer","","1210","Wien","Floridsdorfer Hauptstraße 1","N","J","N","","werner.becher@becher-medien.com","","");
insert into sdfull values (51,1991,"R5B",3,"BÖCK","MARIA","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (52,1991,"R5B",4,"DEIMEL","LEOPOLD","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (53,1991,"R5B",5,"GAIDA","THOMAS","","x",2011,"PCS GmbH","","einfache Programmierungssprachen ( C, xml)","","1120","Wien","Wolfganggasse 45-4T","J","J","J","","Thomas.Gaida@gmx.at","","");
insert into sdfull values (54,1991,"R5B",6,"HOLZMÜLLER","KONRAD","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (55,1991,"R5B",7,"LORENZ","HELMUT","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (56,1991,"R5B",8,"NAGLMAIR","GERALD","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (57,1991,"R5B",9,"PALENSKY","PETER","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (58,1991,"R5B",10,"Perchtold","Erwin","Ing","",2011,"Erwin Perchthold","","Software eigener Studio software pro Tools","","2580","Horn","Hans Krippl Vratic 7","N","N","N","","office@ecertexpress.at","","");
insert into sdfull values (59,1991,"R5B",11,"SCHANDL","CHRISTIAN","Ing","x",2011,"Systema","christian.schandl@systema.info","Beratung & Implementierung von KIS","+43 (0)1 89588814540","1030","Wien","Neulinggasse 29","J","N","N","","","06648415878","");
insert into sdfull values (60,1991,"R5B",12,"SCHMID","ANDREAS","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (61,1991,"R5B",13,"SCHREIDL","GERALD","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (62,1991,"R5B",14,"TICHY","STEFAN","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (63,1991,"R5B",15,"WEISER","MARTIN","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (64,1996,"R5",1,"Arrocker","Stefan","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (65,1996,"R5",2,"Buchgraber","Rudolf","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (66,1996,"R5",3,"Dick","Dieter","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (67,1996,"R5",4,"Essl","Hanno","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (68,1996,"R5",5,"Greill","Heinz","","x",2011,"Bosch","heinz.greill@at.bosch.com","Softwareprojekte","","1110","Wien","Geiereckstraße 6","J","J","J","","","","");
insert into sdfull values (69,1996,"R5",6,"Gschweidl","Manfred","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (70,1996,"R5",7,"Katt","Matthias","Ing","",2011,"Siemens","matthias.katt@siemens.com","Ausbildung","+43 (0) 5170731255","1210","Wien","Ruthnergasse 3","N","N","N","","","","");
insert into sdfull values (71,1996,"R5",8,"Leidler","Roman","","x",2011,"Siemens AG Österreich - Energy Sector","roman.leidler@siemens.com","IBS- Techniker für Schutztechnik (6kV - 400kV)","","1210","Wien","Ruthergasse 3","N","N","N","","","","");
insert into sdfull values (72,1996,"R5",9,"Mantler","Bernhard","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (73,1996,"R5",10,"Nikodym","Markus","","",2011,"Siemens","","Trainer","","1210","Wien","Ruthnergasse 3","J","J","J","","","","");
insert into sdfull values (74,1996,"R5",11,"Oesterreicher","Gerhard","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (75,1996,"R5",12,"Pöhn","Reinhard","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (76,1996,"R5",13,"Pribitzer","Christian","","x",2011,"Rechenzentrum Informations & Telemkommunikationstechnik","christian.pribitzer@wien.gv.at","Personalführung, Produkt&Projektmanagement","","1010","Wien","Rathausstraße","J","","N","","christian.pribitzer@gmx.at","","");
insert into sdfull values (77,1996,"R5",14,"Richnovsky","Dominik","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (78,1996,"R5",15,"Schramböck","Matthias","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (79,1996,"R5",16,"Stürmer","Christian","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (80,1996,"R5",17,"Taurok","Robert","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (81,1996,"R5",18,"Wernhart","Rainer","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (82,1996,"R5",19,"Wessner","Wilfried","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (83,1996,"R5",20,"Ziegler","Gernot","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (84,1996,"RF4",1,"Dunkl","Friedrich","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (85,1996,"RF4",2,"Gavrikov","Alexej","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (86,1996,"RF4",3,"Graf","Willibald","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (87,1996,"RF4",4,"Grausam","Thomas","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (88,1996,"RF4",5,"Hammermüller","Thomas","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (89,1996,"RF4",6,"Harauer","Martin","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (90,1996,"RF4",7,"Kocourek","Jaroslav","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (91,1996,"RF4",8,"Roth","Wolfgang Armin","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (92,1996,"RF4",9,"Schichta","Willibald Peter","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (93,1996,"RF4",10,"Schmidt","Ralf","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (94,1996,"RF4",11,"Schmit","Alexander","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (95,1996,"RF4",12,"Vecka","Ladislav","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (96,1996,"RF4",13,"Wartmann","Hannes","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (97,2001,"R5",1,"Auer","Clemens","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (98,2001,"R5",2,"Bachl","Karl","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (99,2001,"R5",3,"Bichler","Martin","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (100,2001,"R5",4,"Bigl","Dominik","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (101,2001,"R5",5,"Buchsbaum","Gerald","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (102,2001,"R5",6,"Czezatke","Andreas","","x",2011,"SMC - Pneumatik","","Anlagen konzipieren, Schulungen","","2100","Korneuburg","Girakstraße 8","J","J","J","","andreas.czezatke@gmx.at","","");
insert into sdfull values (103,2001,"R5",7,"Danzinger","Gregor","","",2011,"Austro Control","","Management, Projektentwicklung","","","","","J","N","J","","gregor.d@aon.at","","");
insert into sdfull values (104,2001,"R5",8,"Fichtinger","Michael","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (105,2001,"R5",9,"Glassl","Markus","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (106,2001,"R5",10,"Hackl","Markus","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (107,2001,"R5",11,"Hietl","Josef","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (108,2001,"R5",12,"Hobel","Christian","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (109,2001,"R5",13,"Kral","Manfred","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (110,2001,"R5",14,"Lederer","Thomas","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (111,2001,"R5",15,"Pinger","Gregor","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (112,2001,"R5",16,"Rupp","Rainer","","",2011,"Jungbunzlauer Austria AG","","Anlagenbau","","","Pernhofen","","N","N","N","","rainer.rupp@gmail.com","","");
insert into sdfull values (113,2001,"R5",17,"Ryback","Michael","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (114,2001,"R5",18,"Schachenhuber","Josef","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (115,2001,"R5",19,"Schöfmann","Bernd","","",2011,"Redl Gastrosysteme","","Hard- und Softwareentwicklung","","2020","Hollabrunn","","","N","N","","bernd.schoefmann@gmx.at","","");
insert into sdfull values (116,2001,"R5",20,"Skopik","Florian","","",2011,"TU Wien","","Scientific Research, Academic Research","","1040","Wien","Karlsplatz 13","N","N","J","","florian.skopik@gmx.at","","");
insert into sdfull values (117,2001,"R5",21,"Weber","Jürgen","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (118,2001,"R5",22,"Weber","Markus","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (119,2001,"R5",23,"Wihsböck","Michael","Mag. Dipl.Ing","x",2011,"Sumetzberger","wihsboeck@summetzberger.at","software development","+43(1) 740 35 372","1110","Wien","Leberstraße 108","J","J","J","","","","");
insert into sdfull values (120,2001,"R5",24,"Zinnagl","Florian","","x",2011,"Siemens IT Solutions and Service","","IT Service Management","","","","","","N","","","florianzinnagl@aon.at","","");
insert into sdfull values (121,2001,"R5",25,"Zistler","Mario","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (122,2001,"RF4",1,"Bauer","Dieter","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (123,2001,"RF4",2,"Bind","Jürgen","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (124,2001,"RF4",3,"Dolinar","Florian-Paul","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (125,2001,"RF4",4,"Hein","Norbert","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (126,2001,"RF4",5,"Icha","Eduard","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (127,2001,"RF4",6,"Nekham","Thomas Josef","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (128,2001,"RF4",7,"Poigenfürst","Andreas","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (129,2001,"RF4",8,"Prunauer","Rudolf","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (130,2001,"RF4",9,"Schober","Markus","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (131,2001,"RF4",10,"Schöllbauer","Stefan","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (132,2001,"RF4",11,"Siegismund","Tilo","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (133,2001,"RF4",12,"Smolak","David Herbert","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (134,2001,"RF4",13,"Stohl","Herbert","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (135,2001,"RF4",14,"Stöckl","Christoph","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (136,2001,"RF4",15,"Syre","Florian","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (137,2001,"RF4",16,"Teichtmeister","Peter","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (138,2001,"RF4",17,"Hornischer","Andreas","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (139,2001,"RF4",18,"Prosenbauer","Markus","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (140,2001,"RF4",19,"Bitt","Günther","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (141,2006,"5AHELI",1,"Berghuber","Stefan","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (142,2006,"5AHELI",2,"Bittermann","Christina","","x",2011,"KBA Mödling","","Automatisierungstechnikerin","","","","","J","J","J","","christina.bittermann@gmx.at","","");
insert into sdfull values (143,2006,"5AHELI",3,"Bittner","Bernhard","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (144,2006,"5AHELI",4,"Butter","Harald","","x",2011,"BIUTEC Gewässeranalytic","","","","","","","N","N","N","","harald.butter@gmx.at","","");
insert into sdfull values (145,2006,"5AHELI",5,"Buzek","Mathias","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (146,2006,"5AHELI",6,"Denner","Gottfried","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (147,2006,"5AHELI",7,"Egger","Katharina","","",2011,"","","","","","","","","","","","egger.kathi@gmail.com","","");
insert into sdfull values (148,2006,"5AHELI",8,"Groll","Herbert","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (149,2006,"5AHELI",9,"Hisch","Thomas","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (150,2006,"5AHELI",10,"Holub","Markus","","",2011,"TTTech","","Hardwareentwickler","","1040","Wien","Schönbrunnerstraße 7","J","J","N","","","","");
insert into sdfull values (151,2006,"5AHELI",11,"Jascha","Christian","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (152,2006,"5AHELI",12,"Koch","Robert","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (153,2006,"5AHELI",13,"Kronberger","Andreas","","x",2011,"Komunalkredit","","Sofware,Schulungen, Telefonanlagen","","","","Türkenstraße 9","J","N","N","","a.kronberger@ndk.at","","");
insert into sdfull values (154,2006,"5AHELI",14,"Maurer","Wolfgang","","",2011,"","","","","","","","","","","","wolfgang.maurer@gmail.com","","");
insert into sdfull values (155,2006,"5AHELI",15,"Müllner","Franz","","x",2011,"ACP IT Solutions","","Software&Hardware Betreung","","1150","Wien","Pfeiffergasse 2","","N","N","","","","");
insert into sdfull values (156,2006,"5AHELI",16,"Neuzil","Michael","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (157,2006,"5AHELI",17,"Rötzer","Barbara","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (158,2006,"5AHELI",18,"Ruthner","Andreas","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (159,2006,"5AHELI",19,"Schoinz","Mario","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (160,2006,"5AHELI",20,"Schuster","Clemens","","",2011,"","","","","","","","","","","","cl.s@gmx.at","","");
insert into sdfull values (161,2006,"5AHELI",21,"Steiner","Oliver","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (162,2006,"5AHELI",22,"Trauner","Andreas","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (163,2006,"5AHELI",23,"Weinkopf","Martin","","x",2011,"","","","","","","","","","","","weinkopf.martin@gmx.at","","");
insert into sdfull values (164,2006,"5AHELI",24,"Wihsböck","Magdalena","","",2011,"","","","","","","","","","","","magdalena.wihsboeck@gmail.com","","");
insert into sdfull values (165,2006,"5AHELI",25,"Zottl","Martina","","x",2011,"Schmidberger","","Projektabwicklung und Programmieren","","3430","Tulln","Königstörterstraße 7","J","","N","","martina.zottl@gmx.at","","");
insert into sdfull values (166,2006,"5BHELI",1,"Arnauer","Wolfgang","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (167,2006,"5BHELI",2,"Bader","Gregor","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (168,2006,"5BHELI",3,"Cox","Benjamin","","",2011,"Faton (Möller)","","Software,Hardware,Fertigung","","1215","","Sheydgasse 42","J","N","N","","benjamin.cox@gmx.at","","");
insert into sdfull values (169,2006,"5BHELI",4,"Gerstbauer","Martin","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (170,2006,"5BHELI",5,"Glaßner","Sebastian","","",2011,"","","","","","","","","","","","sebastian.glassner@gmx.at","","");
insert into sdfull values (171,2006,"5BHELI",6,"Haan","Markus","","",2011,"ÖBB","","Projektleiter","","1020","Wien","Praterstern 3","J","J","J","","markus_haan@gmx.at","","");
insert into sdfull values (172,2006,"5BHELI",7,"Hagmann","Andreas","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (173,2006,"5BHELI",8,"Herndler","Matthias","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (174,2006,"5BHELI",9,"Höberth","Alexander","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (175,2006,"5BHELI",10,"Höller","Roman","","",2011,"","","","","","","","","","","","romanheller@gmx.at","","");
insert into sdfull values (176,2006,"5BHELI",11,"Honeder","Christian Andreas","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (177,2006,"5BHELI",12,"Kellner","Thomas","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (178,2006,"5BHELI",13,"Kohl","Mario","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (179,2006,"5BHELI",14,"Kraft","Simon","","",2011,"Elektro Leonbacher","","Einkauf, Projektmanagement","02262/73173","2100","Stetten","Gewerbegebiet 12","N","N","N","","simon.kraft@gmx.at","","");
insert into sdfull values (180,2006,"5BHELI",15,"Labschütz","Josef","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (181,2006,"5BHELI",16,"Meißl","David","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (182,2006,"5BHELI",17,"Popp","Markus","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (183,2006,"5BHELI",18,"Prokosch","Christoph","","x",2011,"Zizala Lichtsysteme","","Beschaffung & Freigabe von Zukaufteilen Freigabe von Lieferanten"," +43 74161505-3172","3250","Wieselburg","Scheibbserstraße 17","N","N","","","christoph.prokosch@zkw.at","","");
insert into sdfull values (184,2006,"5BHELI",19,"Schett","Benjamin","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (185,2006,"5BHELI",20,"Schober","Stefan","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (186,2006,"5BHELI",21,"Spazierer","Georg","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (187,2006,"5BHELI",22,"Spielauer","Leopold","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (188,2006,"5BHELI",23,"Straßer","Georg","","",2011,"Riegl Laser Measurement Systems","","Softwareentwicklung, Visualisierung von 3D Laserdaten, Datenverarbeitung","","3580","Horn","Riedenburgstraße 48","J","","","","georg.strasser@wunet.at","","");
insert into sdfull values (189,2006,"5BHELI",24,"Wallner-Haas","Mathias","","x",2011,"Accenture","","Technologie Berater SAP"," + 43/20502 33063","1010","Wien","Schottenring 16","N","N","J","","mathias@wallner-haas.net","","");
insert into sdfull values (190,2006,"5BHELI",25,"Weiskirchner","Michael","","x",2011,"","","","","","","","","","","","michael.weiskirchner@gmail.com","","");
insert into sdfull values (191,2006,"5BHELI",26,"Weiß","Bernhard","","",2011,"","","","","","","","","","","","bernhard.weis@a1.net","","");
insert into sdfull values (192,2006,"4AFEL",1,"Bauer","Roland","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (193,2006,"4AFEL",2,"Böck","Armin","","x",2011,"ÖBB Technischer Service","","Unterstützer des Stl in Themen des QSU, Kommunikation am Standort","","1110","Wien","Grillgasse 48","J","N","J","","armin.boeck@oebb.at","","");
insert into sdfull values (194,2006,"4AFEL",3,"Brechelmacher","Christoph","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (195,2006,"4AFEL",4,"Buchgraber","Roland","","",2011,"Redl","","Computergesteuerte Schaltungen, Instalationen","","2020","Hollabrunn","Baumüllergasse10","N","J","N","","r.buchgraber@redl.co.at","","");
insert into sdfull values (196,2006,"4AFEL",5,"Buresch","Jürgen","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (197,2006,"4AFEL",6,"Eichberger","Markus","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (198,2006,"4AFEL",7,"Glatzenberger","Niklas","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (199,2006,"4AFEL",8,"Goby","Günther","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (200,2006,"4AFEL",9,"Gremliza","Reinhard","","",2011,"SPL Telekomminikation Service GmbH","","Projektleitung/Technischer Support Entwicklung im Mobilfunkbereich","","1210","Wien","Siemensstraße 92","J","","N","","reinhard.gremliza@gmx.at","","");
insert into sdfull values (201,2006,"4AFEL",10,"Hagendorfer","Bernhard","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (202,2006,"4AFEL",11,"Herdlicka","Alexander","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (203,2006,"4AFEL",12,"Huber","Hannes","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (204,2006,"4AFEL",13,"Humpel","Lukas","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (205,2006,"4AFEL",14,"Ivan","Daniel","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (206,2006,"4AFEL",15,"Kanzian","Dominik","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (207,2006,"4AFEL",16,"Markl","Andreas","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (208,2006,"4AFEL",17,"Mauritz","Christian","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (209,2006,"4AFEL",18,"Perko","Michael","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (210,2006,"4AFEL",19,"Sigl","Stefan","","x",2011,"EVN Abfallverwertung","","Wartungen, Störungsbehebungen","","","Mariaentzersdorf","","J","","J","","stefan_sigl@a1.net","","");
insert into sdfull values (211,2006,"4AFEL",20,"Strebl","Johannes","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (212,2006,"4AFEL",21,"Trimmel","Stefan","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (213,2006,"4AFEL",22,"Ullmann","Christian","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (214,2006,"4AFEL",23,"Weber","Andreas","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (215,2006,"4AFEL",24,"Weiss","Thomas","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (216,2006,"4AFEL",25,"Wildner","Rene","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (217,2006,"4AFEL",26,"Würz","Thomas","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (218,2006,"4AFEL",27,"Zachauer","Josef","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (219,2006,"4BFEL",1,"Binder","Klaus","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (220,2006,"4BFEL",2,"Czezatke","Michael","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (221,2006,"4BFEL",3,"Ebinger","Werner","","",2011,"ISI Automotive Gmbh","","Software","","1210","Wien","Scheydgasse 30","N","","J","","","","");
insert into sdfull values (222,2006,"4BFEL",4,"Eckl","Bernhard","","x",0,"","","","","","","","","","","","","","");
insert into sdfull values (223,2006,"4BFEL",5,"Gschwantner","Markus","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (224,2006,"4BFEL",6,"Kabesch","Christian","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (225,2006,"4BFEL",7,"Kitzler","Michael","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (226,2006,"4BFEL",8,"Linda","Michael","","",2011,"BEA","","Wartung und Instandhaltung","","1230","Wien","Lastenstraße 19","J","N","N","","michael.linda@aon.at","","");
insert into sdfull values (227,2006,"4BFEL",9,"Markon","Rene","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (228,2006,"4BFEL",10,"Pauritsch","Markus","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (229,2006,"4BFEL",11,"Popp","Roman","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (230,2006,"4BFEL",12,"Reingruber","Gerald","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (231,2006,"4BFEL",13,"Sakurai","Ikuma","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (232,2006,"4BFEL",14,"Smeibidlo","Manuel","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (233,2006,"4BFEL",15,"Steiner","Daniel","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (234,2006,"4BFEL",16,"Ta","Huyen Dung","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (235,2006,"4BFEL",17,"Vecera","Rafael","","",2011,"Magna Steyr","","Automobilzulieferer","","8261","Sinabelkirchen","Tesma Allee 1","J","J","J","","rafael.vecera@magnasteyr.com","","");
insert into sdfull values (236,2006,"4BFEL",18,"Vögerl","Thomas","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (237,2006,"4BFEL",19,"Weixelbaum","Christoph","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (238,2006,"4BFEL",20,"Winkler","Klaus","","",0,"","","","","","","","","","","","","","");
insert into sdfull values (239,2006,"4BFEL",21,"Winter-Altermann","Michael","","",2011,"Poyer","","Anlagenbau im Broadcastbereich","","3004","Ried am reiderberg","Linzerstraße 20","N","N","J","","michael.winter@gmail.com","","");
insert into sdfull values (240,2006,"4BFEL",22,"Zellhofer","Michael","","",0,"","","","","","","","","","","","","","");
