insert into standort (sid, sname) values (1,"W096");
insert into standort (sid, sname) values (2,"W109");
insert into standort (sid, sname) values (3,"W92");
insert into standort (sid, sname) values (4,"W91");
insert into standort (sid, sname) values (5,"W094");
insert into standort (sid, sname) values (6,"Keller");
insert into standort (sid, sname) values (7,"W13");
insert into standort (sid, sname) values (8,"W110");
insert into standort (sid, sname) values (9,"TU08a");
insert into standort (sid, sname) values (10,"W091");
insert into standort (sid, sname) values (11,"W092");


insert into firma (fid, fname) values (1,"Fluke");
insert into firma (fid, fname) values (2,"AEG");
insert into firma (fid, fname) values (3,"HTL");
insert into firma (fid, fname) values (4,"Agilent");
insert into firma (fid, fname) values (5,"BBC/Goerz/Metrawatt");
insert into firma (fid, fname) values (6,"Servogor");
insert into firma (fid, fname) values (7,"Leybold");
insert into firma (fid, fname) values (8,"Benedikt&Jaeger");
insert into firma (fid, fname) values (9,"A-TEK");
insert into firma (fid, fname) values (10,"BWD Instruments PTY LTD");
insert into firma (fid, fname) values (11,"Deumo");
insert into firma (fid, fname) values (12,"Farnell");
insert into firma (fid, fname) values (13,"LeCroy");
insert into firma (fid, fname) values (14,"FUG");
insert into firma (fid, fname) values (15,"Roline");
insert into firma (fid, fname) values (16,"Goerz");
insert into firma (fid, fname) values (17,"Josef Zelisko");
insert into firma (fid, fname) values (18,"Norma");
insert into firma (fid, fname) values (19,"Tektronix");
insert into firma (fid, fname) values (20,"Gossen");
insert into firma (fid, fname) values (21,"HPS");
insert into firma (fid, fname) values (22,"");
insert into firma (fid, fname) values (23,"Cisco");
insert into firma (fid, fname) values (24,"HP");
insert into firma (fid, fname) values (25,"Datentechnik");
insert into firma (fid, fname) values (26,"JJ LOYD");
insert into firma (fid, fname) values (27,"ELWE");
insert into firma (fid, fname) values (28,"Instruments");
insert into firma (fid, fname) values (29,"Interstate");
insert into firma (fid, fname) values (30,"Jaquet");
insert into firma (fid, fname) values (31,"KEITHLEY");
insert into firma (fid, fname) values (32,"3Com");
insert into firma (fid, fname) values (33,"National_Instruments");
insert into firma (fid, fname) values (34,"LEM");
insert into firma (fid, fname) values (35,"Lucas-Nuelle");
insert into firma (fid, fname) values (36,"Metrawatt");
insert into firma (fid, fname) values (37,"NANO 80");
insert into firma (fid, fname) values (38,"Hoecherl & Hackl GmbH");
insert into firma (fid, fname) values (39,"Bay Networks");
insert into firma (fid, fname) values (40,"TIMONTA");
insert into firma (fid, fname) values (41,"Busch & Jaeger");
insert into firma (fid, fname) values (42,"Oltronix");
insert into firma (fid, fname) values (43,"Ono Sokki");
insert into firma (fid, fname) values (44,"Philips");
insert into firma (fid, fname) values (45,"TES");
insert into firma (fid, fname) values (46,"Houston Instruments");
insert into firma (fid, fname) values (47,"SketchMate");
insert into firma (fid, fname) values (48,"Nikon");
insert into firma (fid, fname) values (49,"Rohde&Schwarz");
insert into firma (fid, fname) values (50,"RS-Components");
insert into firma (fid, fname) values (51,"Siemens");
insert into firma (fid, fname) values (52,"ABB");
insert into firma (fid, fname) values (53,"Lenze");
insert into firma (fid, fname) values (54,"Bernegger&Rainer");
insert into firma (fid, fname) values (55,"Mecc Alte");
insert into firma (fid, fname) values (56,"Zumtobel");
insert into firma (fid, fname) values (57,"ISO-Tech");
insert into firma (fid, fname) values (58,"THURLBY");
insert into firma (fid, fname) values (59,"Wavetek");
insert into firma (fid, fname) values (60,"Wiener Schwachstromwerke");
insert into firma (fid, fname) values (61,"Sugawara");
insert into firma (fid, fname) values (62,"UEI");
insert into firma (fid, fname) values (63,"WaagenSchrenk");
insert into firma (fid, fname) values (64,"Texas Instrument");
insert into firma (fid, fname) values (65,"EPIA");
insert into firma (fid, fname) values (66,"Conrad");
insert into firma (fid, fname) values (67,"Multitech");
insert into firma (fid, fname) values (68,"TTi");
insert into firma (fid, fname) values (69,"Metrix");
insert into firma (fid, fname) values (70,"Huber&Suhner");
insert into firma (fid, fname) values (71,"SI ");
insert into firma (fid, fname) values (72,"Meterman");
insert into firma (fid, fname) values (73,"ERB");
insert into firma (fid, fname) values (74,"HP ");
insert into firma (fid, fname) values (75,"Trenz");
insert into firma (fid, fname) values (76,"Pioneer");
insert into firma (fid, fname) values (77,"dbx");
insert into firma (fid, fname) values (78,"Behringer");
insert into firma (fid, fname) values (79,"Execel by Seas");
insert into firma (fid, fname) values (80,"CA21 RE4x/DC");
insert into firma (fid, fname) values (81,"TINI");
insert into firma (fid, fname) values (82,"Toshiba");
insert into firma (fid, fname) values (83,"Optoma");
insert into firma (fid, fname) values (84,"Kolbinger");
insert into firma (fid, fname) values (85,"Vivanco");
insert into firma (fid, fname) values (86,"Keithley");
insert into firma (fid, fname) values (87,"Stabo");
insert into firma (fid, fname) values (88,"Lem");
insert into firma (fid, fname) values (89,"Grundig");
insert into firma (fid, fname) values (90,"Conitec");
insert into firma (fid, fname) values (91,"Altium");
insert into firma (fid, fname) values (92,"Tenma");
insert into firma (fid, fname) values (93,"Metex");
insert into firma (fid, fname) values (94,"K&H");
insert into firma (fid, fname) values (95,"SUNIX");
insert into firma (fid, fname) values (96,"Picotech");
insert into firma (fid, fname) values (97,"Kathrein");
insert into firma (fid, fname) values (98,"Forson");
insert into firma (fid, fname) values (99,"AMD");
insert into firma (fid, fname) values (100,"MOXA");
insert into firma (fid, fname) values (101,"RUSA");
insert into firma (fid, fname) values (102,"Zelisko");
insert into firma (fid, fname) values (103,"EK");
insert into firma (fid, fname) values (104,"Kyoritsu");
insert into firma (fid, fname) values (105,"Moeller");
insert into firma (fid, fname) values (106,"Elin");
insert into firma (fid, fname) values (107,"VEE");
insert into firma (fid, fname) values (108,"AEP");
insert into firma (fid, fname) values (109,"Analog Devices");
insert into firma (fid, fname) values (110,"Gebhardt");
insert into firma (fid, fname) values (111,"SuperStack");
insert into firma (fid, fname) values (112,"Wimberger");
insert into firma (fid, fname) values (113,"Telemecanique");
insert into firma (fid, fname) values (114,"trafomodern");
insert into firma (fid, fname) values (115,"VDE");
insert into firma (fid, fname) values (116,"Landis");
insert into firma (fid, fname) values (117,"Cherry");
insert into firma (fid, fname) values (118,"Tiger");
insert into firma (fid, fname) values (119,"YeongYang");
insert into firma (fid, fname) values (120,"Miniboeck");
insert into firma (fid, fname) values (121,"Creative_Labs");
insert into firma (fid, fname) values (122,"Acer");
insert into firma (fid, fname) values (123,"Cullmann");
insert into firma (fid, fname) values (124,"Stannol");
insert into firma (fid, fname) values (125,"Omicron Lab");
insert into firma (fid, fname) values (126,"F.W. Bell");
insert into firma (fid, fname) values (127,"Escort");
insert into firma (fid, fname) values (128,"Hameg Instruments");
insert into firma (fid, fname) values (129,"Anritsu");
insert into firma (fid, fname) values (130,"ABB Goerz");
insert into firma (fid, fname) values (131,"GPL");
insert into firma (fid, fname) values (132,"Excel");
insert into firma (fid, fname) values (133,"I.T. Electronic GmbH");
insert into firma (fid, fname) values (134,"AV-JEFE");
insert into firma (fid, fname) values (135,"Velleman");
insert into firma (fid, fname) values (136,"Multikontakt");
insert into firma (fid, fname) values (137,"Firmware Upgrade 2.0.0");
insert into firma (fid, fname) values (138,"BBC");
insert into firma (fid, fname) values (139,"Schlumberger");
insert into firma (fid, fname) values (140,"Pionier");
insert into firma (fid, fname) values (141,"Raytek");
insert into firma (fid, fname) values (142,"Testo");
insert into firma (fid, fname) values (143,"Korona");
insert into firma (fid, fname) values (144,"PCQT");
insert into firma (fid, fname) values (145,"VEEX-VEPAL");
insert into firma (fid, fname) values (146,"ACTERNA");
insert into firma (fid, fname) values (147,"LUXFORM");
insert into firma (fid, fname) values (148,"TRILUX");
insert into firma (fid, fname) values (149,"Xilinx");
insert into firma (fid, fname) values (150,"REO");
insert into firma (fid, fname) values (151,"Mentor II");
insert into firma (fid, fname) values (152,"Delta");
insert into firma (fid, fname) values (153,"OHO-Elektronik");
insert into firma (fid, fname) values (154,"NTI");
insert into firma (fid, fname) values (155,"EATON/ABB");
insert into firma (fid, fname) values (156,"EATON ");
insert into firma (fid, fname) values (157,"F&G");
insert into firma (fid, fname) values (158,"EATON");
insert into firma (fid, fname) values (159,"Schrack");
insert into firma (fid, fname) values (160,"ELABO");
insert into firma (fid, fname) values (161,"WAGO");
insert into firma (fid, fname) values (162,"Coherent,Silberbauer");
insert into firma (fid, fname) values (163,"Bernstein");
insert into firma (fid, fname) values (164,"P-Drive");
insert into firma (fid, fname) values (165,"E&A");
insert into firma (fid, fname) values (166,"Homefibre");
insert into firma (fid, fname) values (167,"ARM Cortex");
insert into firma (fid, fname) values (168,"TechTools");
insert into firma (fid, fname) values (169,"Voltcraft");
insert into firma (fid, fname) values (170,"Socket");
insert into firma (fid, fname) values (171,"IFM");
insert into firma (fid, fname) values (172,"Compra");
insert into firma (fid, fname) values (173,"Maxon");
insert into firma (fid, fname) values (174,"Control Techniques");
insert into firma (fid, fname) values (175,"Loxone");
insert into firma (fid, fname) values (176,"Ellisys");
insert into firma (fid, fname) values (177,"Rigol");
insert into firma (fid, fname) values (178,"Wuerth Elektronik");
insert into firma (fid, fname) values (179,"Oriental Motors");
insert into firma (fid, fname) values (180,"Staudinger");
insert into firma (fid, fname) values (181,"Tools At Work");
insert into firma (fid, fname) values (182,"Nexus7 ASUS");
insert into firma (fid, fname) values (183,"Samsung");
insert into firma (fid, fname) values (184,"Apple");
insert into firma (fid, fname) values (185,"EAC");
insert into firma (fid, fname) values (186,"FLIR");
insert into firma (fid, fname) values (187,"Trafomodern");
insert into firma (fid, fname) values (188,"Nemo");
insert into firma (fid, fname) values (189,"HAEFELY");
insert into firma (fid, fname) values (190,"Chase");
insert into firma (fid, fname) values (191,"Schloeder");
insert into firma (fid, fname) values (192,"Brueel & Kjaer");
insert into firma (fid, fname) values (193,"Aim");
insert into firma (fid, fname) values (194,"Little Bits");
insert into firma (fid, fname) values (195,"Raspberry Pi");
insert into firma (fid, fname) values (196,"Peter Electronic");
insert into firma (fid, fname) values (197,"Ekahau");
insert into firma (fid, fname) values (198,"Janitza");
insert into firma (fid, fname) values (199,"ELV");
insert into firma (fid, fname) values (200,"Logitech");
insert into firma (fid, fname) values (201,"G-Tec");

insert into kategorie (kid, kname) values (1,"Oszilloskop");
insert into kategorie (kid, kname) values (2,"Motor");
insert into kategorie (kid, kname) values (3,"Uebungs-und Laboraufbauten");
insert into kategorie (kid, kname) values (4,"Lehrsysteme");
insert into kategorie (kid, kname) values (5,"Hochfrequenztechnik");
insert into kategorie (kid, kname) values (6,"Drucker / Plotter");
insert into kategorie (kid, kname) values (7,"Messgeraet");
insert into kategorie (kid, kname) values (8,"Widerstand");
insert into kategorie (kid, kname) values (9,"Steckbrett");
insert into kategorie (kid, kname) values (10,"Netzgeraet");
insert into kategorie (kid, kname) values (11,"Transformator");
insert into kategorie (kid, kname) values (12,"Funktionsgenerator");
insert into kategorie (kid, kname) values (13,"Leistungselektronik");
insert into kategorie (kid, kname) values (14,"EMV");
insert into kategorie (kid, kname) values (15,"automatisierte_Messsysteme");
insert into kategorie (kid, kname) values (16,"Netzwerktechnik");
insert into kategorie (kid, kname) values (17,"Audiotechnik");
insert into kategorie (kid, kname) values (18,"Dekaden");
insert into kategorie (kid, kname) values (19,"Digitaltechnik");
insert into kategorie (kid, kname) values (20,"Mikrocontroller");
insert into kategorie (kid, kname) values (21,"Computer");
insert into kategorie (kid, kname) values (22,"Kapazitaet");
insert into kategorie (kid, kname) values (23,"Induktivitaet");
insert into kategorie (kid, kname) values (24,"Beleuchtungstechnik");
insert into kategorie (kid, kname) values (25,"Adapter");
insert into kategorie (kid, kname) values (26,"Schalter");
insert into kategorie (kid, kname) values (27,"Werkzeug");
insert into kategorie (kid, kname) values (28,"Computer ");
insert into kategorie (kid, kname) values (29,"Messgeraet ");
insert into kategorie (kid, kname) values (30,"Servo");
insert into kategorie (kid, kname) values (31,"");
insert into kategorie (kid, kname) values (32,"Bedienungsanleitung");
insert into kategorie (kid, kname) values (33,"LWL-Technik");
insert into kategorie (kid, kname) values (34,"Geraet");


insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (01,11,36,1);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (02,10,35,2);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (03,9,34,3);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (04,8,33,4);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (05,7,32,5);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (06,6,31,6);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (07,5,30,7);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (08,4,29,8);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (09,3,28,9);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (10,2,27,10);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (11,1,26,11);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (12,1,25,12);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (13,2,24,13);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (14,3,23,14);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (15,4,22,15);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (16,5,21,16);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (17,6,20,17);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (18,7,19,18);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (19,8,18,19);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (20,9,17,20);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (21,10,16,21);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (22,11,15,22);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (23,11,14,23);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (24,10,13,24);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (25,9,12,25);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (26,8,11,26);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (27,7,10,27);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (28,6,9,28);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (29,5,8,29);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (30,4,7,30);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (31,3,6,31);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (32,2,5,32);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (33,1,4,33);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (34,1,3,34);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (35,1,2,34);
insert into labor (id, standort_sid,firma_fid,kategorie_kid) values (36,1,1,34);
